# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('fuzzy-tool-example', ['fuzzy-tool'])
    obj.source = 'fuzzy-tool-example.cc'

