# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('fuzzy-tool', ['core'])
    module.source = [
        'model/fuzzy-tool.cc',
        'helper/fuzzy-tool-helper.cc',
        'fuzzy.cc',
        ]

    module_test = bld.create_ns3_module_test_library('fuzzy-tool')
    module_test.source = [
        'test/fuzzy-tool-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'fuzzy-tool'
    headers.source = [
        'model/fuzzy-tool.h',
        'helper/fuzzy-tool-helper.h',
        'fuzzy.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

